"""empty message

Revision ID: a3fccbdeabba
Revises: 471d89e24aab
Create Date: 2024-04-22 16:10:41.612577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3fccbdeabba'
down_revision = '471d89e24aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('addressTwo', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['addressTwo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('addressTwo')

    # ### end Alembic commands ###
